terraform_client_id                       = "TO BE REPLACED"
terraform_client_secret                   = "TO BE REPLACED"
zeppelin_client_secret                    = "TO BE REPLACED"
kidsfirst_confidential_apis_client_secret = "TO BE REPLACED"
google_client_id                          = "TO BE REPLACED"
google_client_secret                      = "TO BE REPLACED"
