---
  name: Run Bridgecrew on terraform 
  on:
    push:
      branches-ignore:
        - 'master'
  
  jobs:
    build:
      name: Check IaC rules
      runs-on: ubuntu-latest
      steps:
        # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        - name: Checkout codebase
          uses: actions/checkout@v2
        
        - name: Run Bridgecrew
          id: Bridgecrew
          uses: bridgecrewio/bridgecrew-action@master
          with:
            api-key: ${{ secrets.BRIDGECREW_API_KEY }}
            directory: terraform 
